version: '3.8'
services:
  vpn_1:
    build:
      context: .
    restart: always
    ports:
      - 1080:1081
    env_file: .env1
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "ping 10.101.247.150 -w 5"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  vpn_2:
    build:
      context: .
    restart: always
    ports:
      - 1081:1081
    env_file: .env2
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "ping 172.16.24.200 -w 5"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
