version: '3.8'
services:
  vpn:
    build:
      context: .
    restart: always
    ports:
      - 1081:1081
      - 3389:3389
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "ping $HEALTHCHECK_TARGET_SERVER -w 5"]
      interval: 60s
      timeout: 60s
      retries: 100
      start_period: 30s
    privileged: true
    # tty: true
    # stdin_open: true
