version: '3.8'
services:
  vpn:
    build:
      context: .
    restart: always
    tty: true
    ports:
      - 1081:1081
      - 3389:3389
    env_file: ./.env
    healthcheck:
      test: ["CMD-SHELL", "ping $TARGET_SERVER -w 5"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    privileged: true
