version: '3.8'
services:
  vpn_1:
    build:
      context: .
    restart: always
    ports:
      - 1080:1081
    env_file: .env1
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M 
    platform: linux/arm64/v8
  vpn_2:
    build:
      context: .
    restart: always
    ports:
      - 1081:1081
    env_file: .env2
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M 
    platform: linux/arm64/v8
